name: Build and Run (Receiver)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testcheckerReceiver ./Receiver/*.c
  
    - name: build SenderData
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testcheckerSendData ./SendData/*.c
      
    - name: run
      run: mvn -f ./pom.xml compile exec:java -Dexec.mainClass="sender.SenderInput" | ./testcheckerReceiver

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21
